### ISSUE TITLE
Usage guidance for SystemIdle

### ISSUE THREAD

**Issue by stijnherreman** [divverence/MarbleTesting#4]
I'm interested in using `await SystemIdle`, @boekabart mentioned this on the Akka.NET Gitter. If I understand correctly, it should help me with waiting for all messages to be handled, before moving on to the assert part of a test.

Currently I have the following test inside a class derived from `Akka.TestKit.Xunit.TestKit`:

```c#
[Fact]
public async Task It_creates_a_workspace_when_it_does_not_exist()
{
    var workspaceCreated = new TaskCompletionSource<object>();
    new CancellationTokenSource(TimeSpan.FromSeconds(1)).Token.Register(() => workspaceCreated.SetCanceled());

    var geometriesServiceClient = Substitute.For<IClient>();
    geometriesServiceClient
        .Workspaces_HeadAsync(Arg.Any<string>())
        .Returns(new SwaggerResponse(((int)HttpStatusCode.NotFound).ToString(), null));
    geometriesServiceClient
        .Workspaces_CreateAsync(Arg.Any<CreateRequest>())
        .Returns(Task.CompletedTask)
        .AndDoes(_ =>
        {
            workspaceCreated.SetResult(null);
        });

    var featureSupervisor = this.CreateFeatureSupervisor(geometriesServiceClient);

    featureSupervisor.Tell(new CreateFeatures(
        this.faker.Random.Word(),
        this.faker.Random.Word(),
        ImmutableHashSet<Feature>.Empty,
        false
        ));

    await workspaceCreated.Task;

    await geometriesServiceClient.Received(1).Workspaces_CreateAsync(Arg.Any<CreateRequest>());
}
```

The goal here is to get rid of `workspaceCreated`, the cancellation token, and the `AndDoes(...)`, and then replace `await workspaceCreated.Task;` with `await SystemIdle;`.

I had a quick attempt with `await Sys.Idle();`, but I'm hitting the exception at https://github.com/divverence/MarbleTesting/blob/4de6e034dfa1eb3f36adc15a28f3ef6eaf00511f/src/Divverence.MarbleTesting.Akka/Async/MultiDispatcherAwaiter.cs#L31

I had a look at the code but I'm not quite sure what other changes to make (nor am I familiar with marble testing), assuming what I'm trying to do is possible in the first place.

**Comment by boekabart** [comment]
https://github.com/divverence/MarbleTesting/blob/develop/src/Divverence.MarbleTesting.Akka/Async/ConfigExtensionsForAsyncTesting.cs
Has the extension helpers to configure your TestKit with the AwaitableDispatcher.

I really have to add some samples...
